# Generated by Django 4.2.29 on 2026-03-23 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee',
            new_name='Student',
        ),
        migrations.RenameField(
            model_name='attendance',
            old_name='employee',
            new_name='student',
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'date')},
        ),
    ]
